Genome_fasta : /lustre/scratch117/cellgen/team218/igs_gp7/Zebrafish/Data/danRer11.fa
Gene_anontation_bed12 : /lustre/scratch117/cellgen/team218/igs_gp7/Zebrafish/Data/danRer11.ensembl.bed12
Gene_anontation_fasta : /lustre/scratch117/cellgen/team218/igs_gp7/Zebrafish/Data/danRer11.ensembl_.fa
GT_AG_U2_5 : /lustre/scratch117/cellgen/team218/igs_gp7/Zebrafish/Data/danRer11_GT_AG_U2_5.good.matrix
GT_AG_U2_3 : /lustre/scratch117/cellgen/team218/igs_gp7/Zebrafish/Data/danRer11_GT_AG_U2_3.good.matrix
conservation_bigwig : /lustre/scratch117/cellgen/team218/igs_gp7/Zebrafish/Data/danRer11.chrom.sizes.bw.sep
ME_len : 30
working_directory : /lustre/scratch117/cellgen/team218/igs_gp7/Zebrafish/
ME_DB : /lustre/scratch117/cellgen/team218/igs_gp7/Zebrafish/Data/VastDb.bed12
Optimize_hard_drive : F
